pr:
  - develop

resources:
  - repo: self

variables:
  imageRepository: "enterprise-chat-api"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: $[format('{0:yyyyMMdd}_{0:HHmm}', pipeline.startTime)]
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              tags: |
                $(tag)
