"""create tables

Revision ID: 9a59146cd0c5
Revises: 43a0373c79c0
Create Date: 2023-09-14 23:54:12.950169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a59146cd0c5'
down_revision = '43a0373c79c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
