"""create tables

Revision ID: 9ab762740d39
Revises: 5d21c9857e33
Create Date: 2023-07-22 15:19:04.499003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab762740d39'
down_revision = '5d21c9857e33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data', sa.String(), nullable=True))
    op.drop_column('users', 'name')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'data')
    # ### end Alembic commands ###
