"""create tables

Revision ID: f4fceedc1051
Revises: ff966531265e
Create Date: 2023-09-23 13:34:04.915784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fceedc1051'
down_revision = 'ff966531265e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
