"""create tables

Revision ID: f6bf03a965a5
Revises: 337264bbed67
Create Date: 2023-08-19 16:39:45.279977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bf03a965a5'
down_revision = '337264bbed67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
